import {
  Code,
  Code2,
  Layout,
  Palette,
  Search,
  Server,
  Smartphone,
  Zap,
  BarChart,
  Globe,
  Database,
  ClipboardList,
  LineChart,
} from "lucide-react"

export const servicesData = [
  {
    title: "Next.js Development",
    icon: Code,
    description: "Modern web applications with server-side rendering",
    fullDescription:
      "I specialize in building high-performance web applications using Next.js, leveraging its powerful features like server-side rendering, static site generation, and API routes to create fast, SEO-friendly websites that provide an exceptional user experience.",
    services: [
      "Websites with improved SEO (SSR and SSG)",
      "Ultra-fast technical blogs",
      "Institutional websites optimized for Google",
      "Personal sites or portfolios with high loading speed",
      "Migrations from traditional React to Next.js",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    gradient: "from-blue-500 to-cyan-600",
    category: "Development",
    featured: true,
  },
  {
    title: "React Native",
    icon: Smartphone,
    description: "Cross-platform mobile apps",
    fullDescription:
      "I develop cross-platform mobile applications using React Native, creating native-like experiences for both iOS and Android from a single codebase, complete with smooth animations, offline capabilities, and integration with device features.",
    services: [
      "Functional mobile apps for Android/iOS",
      "App MVPs for startups",
      "Booking, e-commerce, or delivery apps",
      "Integration with Firebase or external APIs",
      "Native app-style animations and fluid navigation",
    ],
    technologies: ["React Native", "Expo", "Firebase", "Redux", "Native APIs"],
    gradient: "from-blue-400 to-indigo-500",
    category: "Development",
  },
  {
    title: "Node.js Backend",
    icon: Server,
    description: "Scalable backend solutions with Node.js",
    fullDescription:
      "I build robust and scalable backend systems using Node.js and Express, creating RESTful APIs, authentication systems, and database integrations that power modern web and mobile applications.",
    services: [
      "Create simple backends for apps or forms",
      "Basic authentication (login/register)",
      "Endpoints for custom REST APIs",
      "Integration of forms with databases or email",
      "Webhooks for third-party automations",
    ],
    technologies: ["Node.js", "Express", "MongoDB", "PostgreSQL", "JWT"],
    gradient: "from-blue-400 to-cyan-500",
    category: "Development",
  },
  {
    title: "Technical SEO",
    icon: Search,
    description: "Search engine optimization",
    fullDescription:
      "I implement technical SEO best practices to improve your website's visibility in search engines, focusing on site structure, performance optimization, semantic markup, and other technical aspects that help search engines understand and rank your content.",
    services: [
      "Technical SEO audit for existing sites",
      "Optimization of semantic structure and meta tags",
      "Implementation of Core Web Vitals",
      "Integration of SEO on sites developed from scratch",
      "Technical advice for content you want to rank",
    ],
    technologies: ["Schema.org", "Google Search Console", "Lighthouse", "Core Web Vitals", "Analytics"],
    gradient: "from-orange-400 to-amber-500",
    category: "Marketing",
  },
  {
    title: "React Development",
    icon: Code2,
    description: "Frontend development",
    fullDescription:
      "I build modern, interactive user interfaces with React, creating responsive, accessible, and performant web applications that provide an exceptional user experience across all devices and browsers.",
    services: [
      "Development of dashboards, portals, and administrative panels",
      "Reusable and custom components",
      "SPAs with complex logic and global states",
      "Integration with APIs and databases",
      "Frontends for SaaS or internal platforms",
    ],
    technologies: ["React", "Redux", "TypeScript", "Styled Components", "React Query"],
    gradient: "from-blue-400 to-indigo-600",
    category: "Development",
  },
  // --- NUEVAS TARJETAS DE SERVICIOS ---
  {
    title: "HTML (Hypertext Markup Language)",
    icon: Layout,
    description: "The foundation of the web, providing the structure for all websites and applications.",
    fullDescription:
      "HTML is the foundation of the web, providing the structure for all websites and applications. It defines the meaning and structure of web content, enabling the creation of rich, interactive user experiences.",
    services: [
      "Semantic HTML for improved SEO and accessibility",
      "Clean, well-structured code for maintainability",
      "Responsive markup for mobile-first designs",
      "Integration with CSS and JavaScript for dynamic experiences",
      "Optimization for fast loading times",
    ],
    technologies: ["HTML5", "Semantic HTML", "WAI-ARIA", "HTML Templates", "Responsive Design"],
    gradient: "from-blue-300 to-cyan-500",
    category: "Development",
  },
  {
    title: "CSS (Cascading Style Sheets)",
    icon: Palette,
    description: "Brings life to the web, controlling the visual presentation of HTML content.",
    fullDescription:
      "CSS brings life to the web, controlling the visual presentation of your HTML content. It defines colors, layouts, animations, and responsive behavior, ensuring a seamless user experience across devices.",
    services: [
      "Advanced styling with modern CSS (Flexbox, Grid)",
      "Responsive design for mobile and desktop",
      "Custom animations and transitions",
      "Efficient use of preprocessors (Sass, Less)",
      "Component-based styling for scalable projects",
    ],
    technologies: ["CSS3", "Sass", "Flexbox", "Grid", "CSS Modules", "Tailwind CSS", "Styled Components"],
    gradient: "from-blue-400 to-cyan-600",
    category: "Development",
  },
  {
    title: "JavaScript (JS)",
    icon: Zap,
    description: "Powers the dynamic behavior of websites, enabling interactivity and advanced functionality.",
    fullDescription:
      "JavaScript powers the dynamic behavior of websites, enabling interactivity and advanced functionality. It’s the language behind real-time updates, animations, and complex user interactions.",
    services: [
      "Dynamic, client-side scripting for rich interactions",
      "DOM manipulation and event handling",
      "Integration with RESTful APIs and web services",
      "Asynchronous programming with Promises and Async/Await",
      "Modern JavaScript frameworks (React, Next.js, Vue.js)",
    ],
    technologies: ["ES6+", "Vanilla JS", "jQuery", "AJAX", "JSON", "APIs", "TypeScript"],
    gradient: "from-blue-500 to-indigo-500",
    category: "Development",
  },
  {
    title: "Flutter (Cross-Platform App Development)",
    icon: Smartphone,
    description: "Build natively compiled apps from a single codebase",
    fullDescription:
      "Flutter is a powerful framework for building natively compiled, cross-platform mobile, web, and desktop applications from a single codebase. It delivers high-performance apps with a polished, native feel and rich user experiences.",
    services: [
      "Cross-platform app development for iOS, Android, and Web",
      "High-performance UIs with custom animations and transitions",
      "State management with Provider, Riverpod, or Bloc",
      "Integration with APIs, Firebase, and third-party services",
      "Pixel-perfect designs with Flutter widgets and Material/Cupertino styling",
      "Native feature integration (geolocation, camera, push notifications)",
    ],
    technologies: ["Dart", "Flutter", "Firebase", "Riverpod", "Bloc", "Provider", "FlutterFlow", "Material Design", "Cupertino Design"],
    gradient: "from-blue-600 to-cyan-600",
    category: "Development",
    featured: true,
  },
  // --- NUEVAS TARJETAS DE DISEÑO ---
  {
    title: "UI/UX Strategy (User-Centric Design Approach)",
    icon: Search,
    description: "Creating seamless and impactful user experiences",
    fullDescription:
      "UI/UX Strategy is the foundation of every successful digital product, focusing on creating seamless and impactful user experiences. It aligns business goals with user needs, ensuring intuitive and visually appealing designs that drive engagement and conversion.",
    services: [
      "User journey mapping and persona creation",
      "Information architecture and user flows",
      "Data-driven decision making through user research",
      "Conversion rate optimization (CRO) strategies",
      "Wireframing and prototyping for rapid validation",
      "Usability testing and feedback analysis",
    ],
    technologies: ["Figma", "Adobe XD", "Sketch", "Hotjar", "Google Analytics", "Miro", "Overflow", "Balsamiq"],
    gradient: "from-purple-500 to-pink-500",
    category: "Design",
  },
  {
    title: "Design Systems",
    icon: Layout,
    description: "The backbone of scalable design",
    fullDescription:
      "Design Systems are the backbone of scalable design, providing a single source of truth for teams to build consistent, cohesive, and efficient digital products. They streamline the design process and ensure brand consistency across all platforms.",
    services: [
      "Creation of scalable design systems",
      "Design token management for consistency",
      "Atomic design methodology",
      "UI kits and reusable component libraries",
      "Documentation for design and development alignment",
      "Visual hierarchy and responsive design principles",
    ],
    technologies: ["Figma", "Adobe XD", "Sketch", "Zeroheight", "Storybook", "Framer", "Design Tokens", "Tailwind CSS", "Chakra UI", "MUI"],
    gradient: "from-violet-500 to-purple-600",
    category: "Design",
  },
  {
    title: "UI/UX Design",
    icon: Palette,
    description: "User experience design",
    fullDescription:
      "I create intuitive and visually appealing user interfaces that enhance the user experience, focusing on usability, accessibility, and visual design to create products that are both beautiful and functional.",
    services: [
      "Complete app and website design",
      "UX audits and improvements to existing workflows",
      "Navigable prototyping with Figma",
      "Creation of scalable design systems",
      "Visual redesign of brands or products",
    ],
    technologies: ["Figma", "Adobe XD", "Sketch", "Design Systems", "Prototyping"],
    gradient: "from-purple-400 to-fuchsia-500",
    category: "Design",
    featured: true,
  },
  {
    title: "Full-Stack Development",
    icon: Globe,
    description: "End-to-end web application development",
    fullDescription:
      "I provide comprehensive full-stack development services, handling everything from database design and backend API development to frontend user interfaces and deployment, creating complete, production-ready applications.",
    services: [
      "Complete web application development",
      "Database design and implementation",
      "API development and integration",
      "Frontend user interface development",
      "Deployment and maintenance",
    ],
    technologies: ["JavaScript", "TypeScript", "Node.js", "React", "MongoDB", "PostgreSQL"],
    gradient: "from-sky-500 to-blue-600",
    category: "Development",
  },
  {
    title: "Database Design",
    icon: Database,
    description: "Efficient data storage solutions",
    fullDescription:
      "I design and implement efficient database structures that optimize data storage, retrieval, and management, ensuring your application can scale while maintaining performance and data integrity.",
    services: [
      "Database schema design",
      "Data migration and transformation",
      "Query optimization",
      "Database performance tuning",
      "NoSQL and SQL database implementation",
    ],
    technologies: ["MongoDB", "PostgreSQL", "MySQL", "Firebase", "Redis"],
    gradient: "from-blue-400 to-indigo-600",
    category: "Development",
  },
  {
    title: "Workflow Automation",
    icon: Zap,
    description: "Business process automation",
    fullDescription:
      "I automate repetitive tasks and business processes to increase efficiency and reduce manual work, connecting various tools and services to create seamless workflows that save time and reduce errors.",
    services: [
      "Automation of repetitive tasks (e.g., emailing, invoicing, CRM)",
      "Connection between Webflow/WordPress and Airtable, Notion, or Google Sheets",
      "Smart forms with approval flow",
      "Automated chatbots for WhatsApp or websites",
      "Integration between marketing and operations",
    ],
    technologies: ["Zapier", "Make", "Airtable", "Notion", "Google Apps Script"],
    gradient: "from-orange-400 to-amber-500",
    category: "Marketing",
  },
  {
    title: "Google Ads",
    icon: BarChart,
    description: "Performance marketing",
    fullDescription:
      "I set up and optimize Google Ads campaigns to drive targeted traffic to your website, implementing conversion tracking, audience targeting, and performance optimization to maximize your return on ad spend.",
    services: [
      "Implementation of tags with GTM",
      "Measurement of conversions and key events",
      "Optimization of landing pages for campaigns",
      "Technical diagnosis of non-converting campaigns",
      "Assistance with synchronization between Ads, Analytics, and CRM",
    ],
    technologies: ["Google Ads", "Google Tag Manager", "Google Analytics", "Conversion Tracking", "A/B Testing"],
    gradient: "from-orange-500 to-amber-600",
    category: "Marketing",
  },
  {
    title: "No-Code Solutions",
    icon: Layout,
    description: "Rapid website development",
    fullDescription:
      "I leverage no-code platforms to rapidly build and deploy websites and applications, enabling quick iteration and validation of ideas without the need for extensive development resources.",
    services: [
      "Professional landing pages in record time",
      "Websites for personal brands, local businesses, and digital products",
      "Migration of Figma designs to Webflow or Framer",
      "Self-managed websites for clients",
      "Integration with CRMs, payments, or newsletters",
    ],
    technologies: ["Webflow", "Framer", "WordPress", "Shopify", "Bubble"],
    gradient: "from-blue-500 to-indigo-500",
    category: "Development",
  },
  {
    title: "Product Management",
    icon: ClipboardList,
    description: "Strategic product development and leadership",
    fullDescription:
      "I help businesses define, build, and optimize digital products through strategic planning, team coordination, and data-driven decision making, ensuring products meet both user needs and business objectives.",
    services: [
      "Defining OKRs and key metrics",
      "Creating strategic roadmaps",
      "Managing development and design teams",
      "Designing processes for product lifecycles",
      "Validating ideas and MVPs",
      "Launch strategies and market analysis",
      "Prioritizing features and managing backlogs",
      "Analyzing competitors and market trends",
      "Technical documentation and defining use cases",
      "Optimizing processes for agile delivery",
    ],
    technologies: ["Jira", "Notion", "Miro", "Figma", "Amplitude", "Mixpanel"],
    gradient: "from-green-500 to-emerald-600",
    category: "Product Management",
    featured: true,
  },
]
